language: java

deploy:
  provider: heroku
  app: afternoon-tor-19519
  api_key:
    secure: CdMFXJBTs9Q66Lu6RCVuRfDjHZz8Drb6tJP+2B4jaUf+pF1jO8dwt7tJYwwPQLF+hN7OWHw7YlzgNWLt94teWLrtQijFhMUkFhr1xLcQG+exCsmkls8lHN5JUgonHp4ePdidW2GFX75EEjUQExS29Q3n/5YEzurjpNRjwHZ/wBBZuortU8R73XKOunV3AsDRYeQj2h+rc9UKFbOBqUpEfhaSuJpXLTQAoAQLeWbnTlYIk6u90fdM0Nd4Me4bFXgmHSLMzFhnGC7t+oUXxso0ULUOh98qFoyECOJnW4VAUk/oeZggW7crJYkPTY3aTdBxQi6vk+dx81QljR5in/S0DZPEmFBiC6Xd+cl0Vip55BGdXUcTkZl70Z6OQlVrx8cFfpY5u7R2KasJamIwZw0xY6YDKw2W856xlGXvJU9/uf6RUUJxy0D/o/AB7ZDYi2XTm1IfTlOYxxt1zXqlakTOB/HOW11dTxVLFQ7rHi0U16YltaufVOX+pDjH4gHuPRF5lHe0dQJDkpB7lT3tycz+qQLyPft4dCjp/DKKGVJy9lDcajfHYVps5r8YBPRFcE6NASHgLpWiVYiaBeXUCF3bPqxyX5u4rNGhDhn4BG4RKd+xq1sq/2p3xvyFnbiiQF/2Xr7h4UClS9b+5yStTNun6F96VnRMSbxeLQafBj1c4Ts=
