/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TempJNICpp */

#ifndef _Included_TempJNICpp
#define _Included_TempJNICpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TempJNICpp
 * Method:    shuffle
 * Signature: (Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_TempJNICpp_shuffle
  (JNIEnv *, jobject, jstring, jint, jstring, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
