/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TempJNICpp */

#ifndef _Included_TempJNICpp
#define _Included_TempJNICpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TempJNICpp
 * Method:    answer
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_TempJNICpp_answer
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
